spring:
  application:
    name: sigece

  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false